const restaurantListTypes = {
  FETCH_RESTAURANT_REQUEST: "FETCH_RESTAURANT_REQUEST",
  FETCH_RESTAURANT_SUCCESS: "FETCH_RESTAURANT_SUCCESS",
  FETCH_RESTAURANT_FAILURE: "FETCH_RESTAURANT_FAILURE",

  SET_LIST_ORDER: "SET_LIST_ORDER",
  SET_MAP_CENTER: " SET_MAP_CENTER",
  SET_SELECT_RESTAURANT: "SET_SELECT_RESTAURANT",
  RESTAURANT_NAVIGATION: "RESTAURANT_NAVIGATION",

  SET_MAP_API: "SET_MAP_API",
};

export default restaurantListTypes;
