const restaurantListTypes = {
  FETCH_RESTAURANT_REQUEST: "FETCH_RESTAURANT_REQUEST",
  FETCH_RESTAURANT_SUCCESS: "FETCH_RESTAURANT_SUCCESS",
  FETCH_RESTAURANT_FAILURE: "FETCH_RESTAURANT_FAILURE",
};

export default restaurantListTypes;
