const restaurantListTypes = {
  FETCH_RESTAURANT_REQUEST: "FETCH_RESTAURANT_REQUEST",
  FETCH_RESTAURANT_SUCCESS: "FETCH_RESTAURANT_SUCCESS",
  FETCH_RESTAURANT_FAILURE: "FETCH_RESTAURANT_FAILURE",

  SET_LIST_ORDER: "SET_LIST_ORDER",
  SET_MAP_CENTER: " SET_MAP_CENTER",
  SELECT_RESTAURANT: "SELECT_RESTAURANT",
  RESTAURANT_NAVIGATION: "RESTAURANT_NAVIGATION",
};

export default restaurantListTypes;
